[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
lib_deps =
  bogde/HX711@^0.7.5
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.6
  adafruit/Adafruit SHT4x Library@^1.0.5
  adafruit/RTClib@^2.1.4
  bblanchon/ArduinoJson@^7.2.2